INFO:root:using device: cpu
INFO:root:processing subjects: [1, 5, 6, 7, 8]
INFO:root:Training data loader called. len - 5
INFO:root:processing subjects: [9, 11]
INFO:root:Validation data loader called. len - 5
INFO:root:Start training procedure
Traceback (most recent call last):
  File "/home/datta/lab/HPE3D/src/train.py", line 182, in <module>
    main()
  File "/home/datta/lab/HPE3D/src/train.py", line 106, in main
    optimizer, epoch, vae_type)
  File "/home/datta/lab/HPE3D/src/trainer.py", line 25, in training_epoch
    _log_training_metrics(config, output, vae_type)
  File "/home/datta/lab/HPE3D/src/trainer.py", line 199, in _log_training_metrics
    config.writer.add_scalar(f"Loss/{vae_type}/Train_Loss/kld_loss", output['log']['kld_losss'])
KeyError: 'kld_losss'
